"""Extracted GGFW component: constants."""


TOOL_VERSION = "0.7.1-beta"

TOOL_VERSION_DISPLAY = "0.7.1 beta"

REPORT_SCHEMA = "ggfw-report/v2.11"

EVIDENCE_SCHEMA = "ggfw-evidence/v1.9"

OTP_DECODER_SCHEMA = "ggfw-otp-decoder/v1"

SECURE_BOOT_EVIDENCE_SCHEMA = "ggfw-secure-boot-evidence/v2"

SECURE_BOOT_VALIDATION_SCHEMA = "ggfw-secure-boot-validation/v2.1"

VALIDATION_VALID = 'VALID'

VALIDATION_INVALID = 'INVALID'

VALIDATION_UNVERIFIED = 'UNVERIFIED'

REASON_NONE = 'NONE'

REASON_KEY_UNAVAILABLE = 'KEY_UNAVAILABLE'

REASON_OTP_BINDING_UNAVAILABLE = 'OTP_BINDING_UNAVAILABLE'

REASON_ARTIFACT_NOT_FOUND = 'ARTIFACT_NOT_FOUND'

REASON_SIGNATURE_NOT_PRESENT = 'SIGNATURE_NOT_PRESENT'

REASON_FORMAT_INVALID = 'FORMAT_INVALID'

REASON_CRYPTOGRAPHIC_MISMATCH = 'CRYPTOGRAPHIC_MISMATCH'

REASON_TARGET_SOC_MISMATCH = 'TARGET_SOC_MISMATCH'

REASON_FRESHNESS_POLICY_FAILURE = 'FRESHNESS_POLICY_FAILURE'

REASON_IO_ERROR = 'IO_ERROR'

REASON_KEY_MISMATCH = 'KEY_MISMATCH'
